"use client";

import { useState } from "react";
import Link from "next/link";
import { useTheme } from "@/context/ThemeContext";

export default function HomeDetails() {
  const { theme } = useTheme();
  const isDarkTheme = theme === "dark";
  const isCustomTheme = theme === "custom";

  const [activeNode, setActiveNode] = useState<string>("ingestion");

  const stats = [
    { value: "100%", label: "On-Premises", desc: "Air-gapped deployment for absolute security" },
    { value: "Sovereign", label: "Model Ownership", desc: "Zero data leakage to external APIs" },
    { value: "CPSU/SPSU", label: "Compliance", desc: "Tailored to Indian public sector standards" },
    { value: "Sub-Second", label: "Inference Speed", desc: "Optimized local hardware utilization" }
  ];

  const pillars = [
    {
      title: "Sovereign GenAI Platforms",
      desc: "Deploy localized Large Language Models (LLMs) fine-tuned on your specific regulatory documents, circulars, and historical data. Enables instant querying, automated note-sheet drafting, and synthesis without connecting to the public internet.",
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
      ),
      link: "/solutions"
    },
    {
      title: "Workflow Automation Engines",
      desc: "Streamline cross-department file routing, legacy database migration pipelines, and repetitive administrative workflows. Our intelligent orchestrator automatically categorizes records, flags anomalies, and pre-fills compliance checks.",
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
        </svg>
      ),
      link: "/solutions"
    },
    {
      title: "Decision Intelligence & BI",
      desc: "Turn high-volume telemetry and operational logs into clear, actionable advice. Ideal for heavy industries, power grids, and smart cities requiring predictive maintenance, real-time grid status monitoring, and strategic forecasting.",
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 002 2h2a2 2 0 002-2z" />
        </svg>
      ),
      link: "/solutions"
    }
  ];

  const securityNodes = {
    ingestion: {
      title: "Air-Gapped Data Ingestion",
      desc: "Raw enterprise data is scanned and ingested locally through an isolated pipeline. No connection is established with external public endpoints, eliminating MITM (Man-In-The-Middle) attacks."
    },
    vectordb: {
      title: "Local Vector In-Memory Indexing",
      desc: "Unstructured files (PDFs, spreadsheets, note-sheets) are embedded using local models and saved to a high-performance, on-premises Vector Database. Retrieval is immediate and contextual."
    },
    inference: {
      title: "Private LLM Inference Engine",
      desc: "Queries are processed by a localized LLM (e.g. Llama-3, Qwen) hosted on on-premises GPUs. Answers are generated by matching internal datasets, without cloud telemetry."
    }
  };

  const telemetryNodes = {
    ingestion: {
      nodeId: "NODE-01 / INGESTION",
      status: "ACTIVE & ISOLATED",
      metrics: [
        { label: "Data Pipeline", value: "100% Air-Gapped", type: "badge" },
        { label: "Local Buffer", value: "Verified Safe", type: "success" },
        { label: "MITM Protection", value: "Guaranteed", type: "success" },
        { label: "Sanitization Rate", value: "100%", type: "gauge", progress: 100 }
      ],
      checklist: [
        "Network interface physically isolated",
        "PII and metadata scrubbed locally",
        "Secure directory validation complete",
        "Local buffer sequence initialized"
      ]
    },
    vectordb: {
      nodeId: "NODE-02 / VECTORDB",
      status: "SYNCHRONIZED",
      metrics: [
        { label: "Database Module", value: "pgvector Online", type: "success" },
        { label: "Indexed Records", value: "12,400 Nodes", type: "badge" },
        { label: "Sync Status", value: "Synchronized", type: "success" },
        { label: "Memory Sealing", value: "Sealed", type: "gauge", progress: 100 }
      ],
      checklist: [
        "PostgreSQL pgvector database online",
        "768-dim embeddings mapping synced",
        "HNSW vector index mapped in-memory",
        "Database seal sequence verified"
      ]
    },
    inference: {
      nodeId: "NODE-03 / LLM_CORE",
      status: "COMPLIANT INFERENCE",
      metrics: [
        { label: "Local GPU Temp", value: "62°C", type: "warning" },
        { label: "VRAM Security", value: "Ring-Fenced", type: "success" },
        { label: "Query Verification", value: "Dual-Enforced", type: "badge" },
        { label: "Context Accuracy", value: "99.8%", type: "gauge", progress: 99.8 }
      ],
      checklist: [
        "Llama-3 model loaded securely into VRAM",
        "Prompt injection protection active",
        "Compliance checking rules applied",
        "Telemetry transmission: Disabled"
      ]
    }
  };

  const accentColor = isDarkTheme ? "#06b6d4" : "#36558F";
  const cardBg = isDarkTheme ? "#0A0726" : "#DAF0EE";
  const cardBorder = isDarkTheme ? "rgba(34, 211, 238, 0.1)" : "rgba(64, 121, 140, 0.2)";
  const textColor = isDarkTheme ? "text-slate-400" : "text-[#1A2530]";
  const headingColor = isDarkTheme ? "text-white" : "text-[#1A2530]";

  return (
    <div className="w-full space-y-32 pb-24 relative z-10 max-w-7xl mx-auto px-6">
      
      {/* 1. TRUST STATS DASHBOARD */}
      <section className="pt-4">
        <div 
          style={{
            backgroundColor: isDarkTheme ? "#0A0726" : "#FAF9F6",
            borderColor: cardBorder
          }}
          className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 p-8 border rounded-2xl shadow-xl transition-all duration-300"
        >
          {stats.map((stat, idx) => (
            <div key={idx} className="text-center space-y-2 border-r last:border-none border-white/5 pr-4 last:pr-0">
              <div 
                style={{ color: accentColor }}
                className="text-3xl font-extrabold tracking-tight"
              >
                {stat.value}
              </div>
              <div className={`text-sm font-bold ${headingColor}`}>
                {stat.label}
              </div>
              <p className={`text-xs ${textColor}`}>
                {stat.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* 2. PILLARS OF INTELLIGENCE */}
      <section className="space-y-12">
        <div className="text-center space-y-4">
          <h2 className={`text-3xl sm:text-4xl font-bold tracking-tight ${headingColor}`}>
            Next-Gen Digital Transformation Vectors
          </h2>
          <p className={`text-sm max-w-2xl mx-auto ${textColor}`}>
            Velar builds bespoke enterprise platforms leveraging localized intelligence architectures, designed for extreme operational continuity.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {pillars.map((pillar, idx) => (
            <div
              key={idx}
              style={{
                backgroundColor: cardBg,
                borderColor: cardBorder
              }}
              className="border p-8 rounded-2xl flex flex-col justify-between hover:scale-[1.02] transition-all duration-300 shadow-md group"
            >
              <div className="space-y-4">
                <div 
                  style={{
                    backgroundColor: isDarkTheme ? "rgba(6, 182, 212, 0.1)" : "rgba(54, 85, 143, 0.1)",
                    color: accentColor,
                    borderColor: isDarkTheme ? "rgba(6, 182, 212, 0.2)" : "rgba(54, 85, 143, 0.2)"
                  }}
                  className="w-12 h-12 rounded-xl border flex items-center justify-center"
                >
                  {pillar.icon}
                </div>
                <h3 className={`text-xl font-bold tracking-tight ${headingColor}`}>
                  {pillar.title}
                </h3>
                <p className={`text-sm leading-relaxed ${textColor}`}>
                  {pillar.desc}
                </p>
              </div>

              <div className="pt-6">
                <Link
                  href={pillar.link}
                  style={{ color: accentColor }}
                  className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2 hover:opacity-85 transition-opacity"
                >
                  <span>Learn More</span>
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                  </svg>
                </Link>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 3. INTERACTIVE SECURITY SCHEMATIC */}
      <section className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        {/* Left Interactive Panel */}
        <div className="lg:col-span-5 space-y-6">
          <span 
            style={{
              color: accentColor,
              backgroundColor: isDarkTheme ? "rgba(6, 182, 212, 0.15)" : "rgba(54, 85, 143, 0.15)",
              borderColor: isDarkTheme ? "rgba(6, 182, 212, 0.3)" : "rgba(54, 85, 143, 0.3)"
            }}
            className="inline-block text-xs font-mono tracking-widest uppercase border px-3 py-1 rounded-full"
          >
            Sovereign Rings
          </span>
          <h2 className={`text-3xl sm:text-4xl font-bold tracking-tight leading-tight ${headingColor}`}>
            Ring-Fenced Compliance Layer Architecture
          </h2>
          <p className={`text-sm leading-relaxed ${textColor}`}>
            Click through our architectural nodes on the dashboard to visualize how data remains safe. We host the entire AI framework on-premises, blocking unauthorized internet access.
          </p>

          <div className="space-y-3">
            {[
              { id: "ingestion", label: "Isolated Ingestion Pipeline" },
              { id: "vectordb", label: "Local Memory & VectorDB" },
              { id: "inference", label: "On-Premises LLM Core" }
            ].map((node) => (
              <button
                key={node.id}
                onClick={() => setActiveNode(node.id)}
                style={{
                  backgroundColor: activeNode === node.id ? cardBg : "transparent",
                  borderColor: activeNode === node.id ? accentColor : "rgba(255, 255, 255, 0.05)"
                }}
                className={`w-full text-left p-4 rounded-xl border flex items-center justify-between cursor-pointer transition-all duration-300 font-medium ${headingColor}`}
              >
                <span>{node.label}</span>
                <div 
                  className={`w-2.5 h-2.5 rounded-full ${
                    activeNode === node.id ? "animate-ping" : "opacity-40"
                  }`}
                  style={{ backgroundColor: accentColor }}
                />
              </button>
            ))}
          </div>
        </div>

        {/* Right Telemetry Dashboard */}
        <div className="lg:col-span-7">
          <div 
            style={{
              backgroundColor: isDarkTheme ? "rgba(10, 7, 38, 0.6)" : "rgba(255, 255, 255, 0.85)",
              borderColor: cardBorder
            }}
            className="w-full border rounded-2xl overflow-hidden shadow-xl flex flex-col min-h-[380px] backdrop-blur-md transition-all duration-300"
          >
            {/* Telemetry Window Header */}
            <div 
              style={{ 
                backgroundColor: isDarkTheme ? "rgba(3, 0, 20, 0.5)" : "rgba(218, 240, 238, 0.4)",
                borderBottomColor: cardBorder 
              }}
              className="px-6 py-4 flex items-center justify-between border-b transition-colors duration-300"
            >
              <div className="flex items-center gap-2">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                </span>
                <span className={`text-[10px] font-bold tracking-widest transition-colors duration-300 uppercase ${isDarkTheme ? "text-slate-400" : "text-[#1A2530]"}`}>
                  Sovereign Telemetry
                </span>
              </div>
              <span 
                style={{ 
                  color: accentColor,
                  backgroundColor: isDarkTheme ? "rgba(6, 182, 212, 0.1)" : "rgba(54, 85, 143, 0.1)",
                  borderColor: isDarkTheme ? "rgba(6, 182, 212, 0.2)" : "rgba(54, 85, 143, 0.2)"
                }}
                className="text-[9px] font-mono tracking-widest border px-2 py-0.5 rounded-full uppercase"
              >
                {telemetryNodes[activeNode as keyof typeof telemetryNodes].nodeId}
              </span>
            </div>

            {/* Telemetry Screen Body */}
            <div className="p-6 flex-1 flex flex-col justify-between gap-6 transition-all duration-300">
              {/* Active Step Details */}
              <div className="space-y-2">
                <div className="flex items-center justify-between gap-4">
                  <h3 className={`text-base font-bold transition-colors duration-300 ${headingColor}`}>
                    {securityNodes[activeNode as keyof typeof securityNodes].title}
                  </h3>
                  <span 
                    className={`text-[9px] font-extrabold px-2 py-0.5 rounded-full tracking-wider flex-shrink-0 ${
                      isDarkTheme 
                        ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" 
                        : "bg-emerald-100 text-emerald-800 border border-emerald-200"
                    }`}
                  >
                    {telemetryNodes[activeNode as keyof typeof telemetryNodes].status}
                  </span>
                </div>
                <p className={`text-xs leading-relaxed transition-colors duration-300 ${textColor}`}>
                  {securityNodes[activeNode as keyof typeof securityNodes].desc}
                </p>
              </div>

              {/* Telemetry Metrics Grid */}
              <div className="grid grid-cols-2 gap-4">
                {telemetryNodes[activeNode as keyof typeof telemetryNodes].metrics.map((metric, idx) => (
                  <div 
                    key={idx}
                    style={{
                      backgroundColor: isDarkTheme ? "rgba(255, 255, 255, 0.02)" : "rgba(54, 85, 143, 0.03)",
                      borderColor: cardBorder
                    }}
                    className="p-3 border rounded-xl flex flex-col justify-between gap-1.5 transition-all duration-300"
                  >
                    <span className="text-[9px] font-semibold text-slate-500 uppercase tracking-wider">
                      {metric.label}
                    </span>
                    {metric.type === "gauge" ? (
                      <div className="space-y-1">
                        <div className="flex items-center justify-between text-[11px] font-bold">
                          <span style={{ color: accentColor }}>{metric.value}</span>
                        </div>
                        <div className={`w-full h-1.5 rounded-full ${isDarkTheme ? "bg-slate-800/80" : "bg-slate-200"} overflow-hidden`}>
                          <div 
                            style={{ 
                              width: `${metric.progress}%`,
                              backgroundColor: accentColor
                            }}
                            className="h-full rounded-full transition-all duration-500"
                          />
                        </div>
                      </div>
                    ) : (
                      <span 
                        style={{ 
                          color: metric.type === "success" 
                            ? (isDarkTheme ? "#34d399" : "#0f766e")
                            : metric.type === "warning"
                            ? (isDarkTheme ? "#fbbf24" : "#b45309")
                            : accentColor 
                        }}
                        className="text-[12px] font-bold tracking-tight"
                      >
                        {metric.value}
                      </span>
                    )}
                  </div>
                ))}
              </div>

              {/* Compliance Verification Checklist */}
              <div 
                style={{ 
                  backgroundColor: isDarkTheme ? "rgba(0, 0, 0, 0.2)" : "rgba(64, 121, 140, 0.03)",
                  borderColor: cardBorder
                }}
                className="p-4 border rounded-xl space-y-2.5 transition-all duration-300"
              >
                <div className="text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1 flex items-center gap-1.5">
                  <svg className="w-3.5 h-3.5 text-emerald-500" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                  </svg>
                  <span>Compliance Verification Audit</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1.5">
                  {telemetryNodes[activeNode as keyof typeof telemetryNodes].checklist.map((item, idx) => (
                    <div key={idx} className="flex items-start gap-2 text-[11px] leading-snug">
                      <svg className="w-3 h-3 text-emerald-500 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                      </svg>
                      <span className={textColor}>{item}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
    </div>
  );
}
