"use client";

import { useState } from "react";
import Link from "next/link";
import { useTheme } from "@/context/ThemeContext";

export default function HomeDetails() {
  const { theme } = useTheme();
  const isDarkTheme = theme === "dark";
  const isCustomTheme = theme === "custom";

  const [activeNode, setActiveNode] = useState<string>("ingestion");

  const stats = [
    { value: "100%", label: "On-Premises", desc: "Air-gapped deployment for absolute security" },
    { value: "Sovereign", label: "Model Ownership", desc: "Zero data leakage to external APIs" },
    { value: "CPSU/SPSU", label: "Compliance", desc: "Tailored to Indian public sector standards" },
    { value: "Sub-Second", label: "Inference Speed", desc: "Optimized local hardware utilization" }
  ];

  const pillars = [
    {
      title: "Sovereign GenAI Platforms",
      desc: "Deploy localized Large Language Models (LLMs) fine-tuned on your specific regulatory documents, circulars, and historical data. Enables instant querying, automated note-sheet drafting, and synthesis without connecting to the public internet.",
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
      ),
      link: "/solutions"
    },
    {
      title: "Workflow Automation Engines",
      desc: "Streamline cross-department file routing, legacy database migration pipelines, and repetitive administrative workflows. Our intelligent orchestrator automatically categorizes records, flags anomalies, and pre-fills compliance checks.",
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
        </svg>
      ),
      link: "/solutions"
    },
    {
      title: "Decision Intelligence & BI",
      desc: "Turn high-volume telemetry and operational logs into clear, actionable advice. Ideal for heavy industries, power grids, and smart cities requiring predictive maintenance, real-time grid status monitoring, and strategic forecasting.",
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 002 2h2a2 2 0 002-2z" />
        </svg>
      ),
      link: "/solutions"
    }
  ];

  const securityNodes = {
    ingestion: {
      title: "Air-Gapped Data Ingestion",
      desc: "Raw enterprise data is scanned and ingested locally through an isolated pipeline. No connection is established with external public endpoints, eliminating MITM (Man-In-The-Middle) attacks.",
      logs: [
        "SYS: Initializing ingestion sequence...",
        "SYS: Directory verification successful.",
        "SEC: Network interface isolated.",
        "SEC: Ingestion stream: 100% Ring-fenced."
      ]
    },
    vectordb: {
      title: "Local Vector In-Memory Indexing",
      desc: "Unstructured files (PDFs, spreadsheets, note-sheets) are embedded using local models and saved to a high-performance, on-premises Vector Database. Retrieval is immediate and contextual.",
      logs: [
        "DB: Checking localized PostgreSQL status...",
        "DB: Vector module (pgvector) online.",
        "DB: Synchronizing 12,400 security nodes...",
        "DB: Indexing successfully complete."
      ]
    },
    inference: {
      title: "Private LLM Inference Engine",
      desc: "Queries are processed by a localized LLM (e.g. Llama-3, Qwen) hosted on on-premises GPUs. Answers are generated by matching internal datasets, without cloud telemetry.",
      logs: [
        "LLM: Checking local GPU temperature: 62°C",
        "LLM: Models loaded into VRAM securely.",
        "LLM: Processing query validation rules...",
        "LLM: Context matching accuracy: 99.8%"
      ]
    }
  };

  const accentColor = isDarkTheme ? "#06b6d4" : "#36558F";
  const cardBg = isDarkTheme ? "#0A0726" : "#DAF0EE";
  const cardBorder = isDarkTheme ? "rgba(34, 211, 238, 0.1)" : "rgba(64, 121, 140, 0.2)";
  const textColor = isDarkTheme ? "text-slate-400" : "text-[#1A2530]";
  const headingColor = isDarkTheme ? "text-white" : "text-[#1A2530]";

  return (
    <div className="w-full space-y-32 pb-24 relative z-10 max-w-7xl mx-auto px-6">
      
      {/* 1. TRUST STATS DASHBOARD */}
      <section className="pt-4">
        <div 
          style={{
            backgroundColor: isDarkTheme ? "#0A0726" : "#FAF9F6",
            borderColor: cardBorder
          }}
          className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 p-8 border rounded-2xl shadow-xl transition-all duration-300"
        >
          {stats.map((stat, idx) => (
            <div key={idx} className="text-center space-y-2 border-r last:border-none border-white/5 pr-4 last:pr-0">
              <div 
                style={{ color: accentColor }}
                className="text-3xl font-extrabold tracking-tight"
              >
                {stat.value}
              </div>
              <div className={`text-sm font-bold ${headingColor}`}>
                {stat.label}
              </div>
              <p className={`text-xs ${textColor}`}>
                {stat.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* 2. PILLARS OF INTELLIGENCE */}
      <section className="space-y-12">
        <div className="text-center space-y-4">
          <h2 className={`text-3xl sm:text-4xl font-bold tracking-tight ${headingColor}`}>
            Next-Gen Digital Transformation Vectors
          </h2>
          <p className={`text-sm max-w-2xl mx-auto ${textColor}`}>
            Velar builds bespoke enterprise platforms leveraging localized intelligence architectures, designed for extreme operational continuity.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {pillars.map((pillar, idx) => (
            <div
              key={idx}
              style={{
                backgroundColor: cardBg,
                borderColor: cardBorder
              }}
              className="border p-8 rounded-2xl flex flex-col justify-between hover:scale-[1.02] transition-all duration-300 shadow-md group"
            >
              <div className="space-y-4">
                <div 
                  style={{
                    backgroundColor: isDarkTheme ? "rgba(6, 182, 212, 0.1)" : "rgba(54, 85, 143, 0.1)",
                    color: accentColor,
                    borderColor: isDarkTheme ? "rgba(6, 182, 212, 0.2)" : "rgba(54, 85, 143, 0.2)"
                  }}
                  className="w-12 h-12 rounded-xl border flex items-center justify-center"
                >
                  {pillar.icon}
                </div>
                <h3 className={`text-xl font-bold tracking-tight ${headingColor}`}>
                  {pillar.title}
                </h3>
                <p className={`text-sm leading-relaxed ${textColor}`}>
                  {pillar.desc}
                </p>
              </div>

              <div className="pt-6">
                <Link
                  href={pillar.link}
                  style={{ color: accentColor }}
                  className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2 hover:opacity-85 transition-opacity"
                >
                  <span>Learn More</span>
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                  </svg>
                </Link>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 3. INTERACTIVE SECURITY SCHEMATIC */}
      <section className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        {/* Left Interactive Panel */}
        <div className="lg:col-span-5 space-y-6">
          <span 
            style={{
              color: accentColor,
              backgroundColor: isDarkTheme ? "rgba(6, 182, 212, 0.15)" : "rgba(54, 85, 143, 0.15)",
              borderColor: isDarkTheme ? "rgba(6, 182, 212, 0.3)" : "rgba(54, 85, 143, 0.3)"
            }}
            className="inline-block text-xs font-mono tracking-widest uppercase border px-3 py-1 rounded-full"
          >
            Sovereign Rings
          </span>
          <h2 className={`text-3xl sm:text-4xl font-bold tracking-tight leading-tight ${headingColor}`}>
            Ring-Fenced Compliance Layer Architecture
          </h2>
          <p className={`text-sm leading-relaxed ${textColor}`}>
            Click through our architectural nodes on the dashboard to visualize how data remains safe. We host the entire AI framework on-premises, blocking unauthorized internet access.
          </p>

          <div className="space-y-3">
            {[
              { id: "ingestion", label: "Isolated Ingestion Pipeline" },
              { id: "vectordb", label: "Local Memory & VectorDB" },
              { id: "inference", label: "On-Premises LLM Core" }
            ].map((node) => (
              <button
                key={node.id}
                onClick={() => setActiveNode(node.id)}
                style={{
                  backgroundColor: activeNode === node.id ? cardBg : "transparent",
                  borderColor: activeNode === node.id ? accentColor : "rgba(255, 255, 255, 0.05)"
                }}
                className={`w-full text-left p-4 rounded-xl border flex items-center justify-between cursor-pointer transition-all duration-300 font-medium ${headingColor}`}
              >
                <span>{node.label}</span>
                <div 
                  className={`w-2.5 h-2.5 rounded-full ${
                    activeNode === node.id ? "animate-ping" : "opacity-40"
                  }`}
                  style={{ backgroundColor: accentColor }}
                />
              </button>
            ))}
          </div>
        </div>

        {/* Right Terminal Sandbox */}
        <div className="lg:col-span-7">
          <div 
            style={{
              backgroundColor: "#030014",
              borderColor: "rgba(255, 255, 255, 0.1)"
            }}
            className="w-full border rounded-2xl overflow-hidden shadow-2xl flex flex-col min-h-[380px]"
          >
            {/* Terminal Window Header */}
            <div className="bg-slate-950 px-4 py-3 flex items-center justify-between border-b border-white/5">
              <div className="flex gap-1.5">
                <span className="w-3 h-3 rounded-full bg-red-500/80" />
                <span className="w-3 h-3 rounded-full bg-yellow-500/80" />
                <span className="w-3 h-3 rounded-full bg-green-500/80" />
              </div>
              <span className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">
                Secure Terminal Sandbox
              </span>
              <div className="w-12" />
            </div>

            {/* Terminal Screen Body */}
            <div className="p-6 flex-1 flex flex-col justify-between font-mono text-xs text-green-400 space-y-4">
              <div className="space-y-1">
                <div className="text-slate-500">// {securityNodes[activeNode as keyof typeof securityNodes].title}</div>
                <p className="text-slate-300 mt-2 leading-relaxed">
                  {securityNodes[activeNode as keyof typeof securityNodes].desc}
                </p>
              </div>

              <div 
                style={{ backgroundColor: "rgba(0,0,0,0.4)" }}
                className="p-4 border border-white/5 rounded-xl space-y-1.5"
              >
                {securityNodes[activeNode as keyof typeof securityNodes].logs.map((log, idx) => (
                  <div key={idx} className="flex gap-2">
                    <span className="text-cyan-400">&gt;</span>
                    <span>{log}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>
      
    </div>
  );
}
